### ISSUE TITLE
Dar de alta libros digitales

### ISSUE THREAD

**Issue by AlejandrodePablo** [AlejandrodePablo/ed-digital-library#11]
#### 💡 Descripción💡
La biblioteca necesita poder agregar nuevos libros digitales. Para ello se añadirán nuevas clases, entre ellas la clase *EBook*, que tendrá los atributos comunes de los libros que sean añadidos a la biblioteca digital.

---

#### 🖥️ Creación de libros digitales

1. Crear la clase *EBook* con sus respectivos atributos
2. Crear el caso de uso que servirá para crear un nuevo libro con los atributos de la clase anteriormente creada.
3. Añadir la clase que servirá para gestionar los datos y almacenarlos en un fichero.
4. Crear una clase en el apartado de "presentación" para que solicite la introducción de dichos datos por pantalla.
5. Actualizar la clase *Main*, q también contiene las llamadas a los metodos de *User*

---

#### 🖊️ ¿Todo en orden?
 - [x]  La clase *EBook* ha sido creada y se utiliza para representar correctamente la información del usuario.
 - [x]  El caso de uso para crear un libro digital ha sido implementado y funciona según los requisitos establecidos.
  - [x] El repositorio de libros digitales se ha desarrollado y se conecta correctamente con la fuente de datos local.
 - [x]  La opción de crear un libro en el menú de la interfaz de libro está funcional y proporciona una 
 experiencia intuitiva para el usuario final.

---

#### 🗓️ 06/05/2024 ->Final
