### ISSUE TITLE
Dar de baja un libro digital

### ISSUE THREAD

**Issue by AlejandrodePablo** [AlejandrodePablo/ed-digital-library#13]
#### 💡 Descripción💡
La biblioteca necesita poder dar de baja libros digitales de su colección. Para ello se añadirán nuevas funcionalidades que permitirán la eliminación de libros digitales de la biblioteca digital.

---

#### 🖥️ Eliminación de libros digitales

1. Crear el caso de uso que permita dar de baja un libro digital de la biblioteca.
2. Añadir la lógica necesaria para eliminar el libro digital de la fuente de datos local.
3. Actualizar la interfaz de presentación para permitir la eliminación de libros digitales.
4. Actualizar la clase *Main* para incluir la opción de dar de baja un libro digital en el menú de la interfaz.

---

#### 🖊️ ¿Todo en orden?
 - [x]  Se ha implementado la funcionalidad para dar de baja libros digitales de la biblioteca.
 - [x]  El caso de uso para dar de baja libros digitales ha sido implementado y funciona según los requisitos establecidos.
 - [x]  La fuente de datos local se actualiza correctamente al dar de baja un libro digital.
 - [x]  La opción de dar de baja un libro digital en el menú de la interfaz de libro está funcional y proporciona una experiencia intuitiva para el usuario final.

---
