### ISSUE TITLE
Listar todos los libros digitales de la biblioteca

### ISSUE THREAD

**Issue by AlejandrodePablo** [AlejandrodePablo/ed-digital-library#16]
#### 💡 Descripción💡
La biblioteca necesita poder listar todos los libros digitales almacenados en su sistema. Para lograr esto, se implementará una funcionalidad que permita recuperar y mostrar todos los libros digitales disponibles en la biblioteca.

---

#### 🖥️ Listar libros digitales

1. Se implementará un nuevo método en la capa de dominio para obtener todos los libros digitales. *(Dominio)*
2. Se agregará una funcionalidad en la capa de datos para recuperar todos los libros digitales almacenados en la fuente de datos. *(Data)*
3. Se actualizará la clase de presentación para permitir la visualización de todos los libros digitales disponibles. *(Presentación)*

---

#### 🖊️ ¿Todo en orden?
 - [x]  Se ha implementado un método en la capa de dominio para obtener todos los libros digitales. 
 - [x]  La capa de datos puede recuperar todos los libros digitales almacenados en la fuente de datos. 
 - [x] La clase de presentación muestra todos los libros digitales disponibles en la biblioteca de manera correcta. 
 - [x]  La funcionalidad ha sido probada exhaustivamente y se ha comprobado que funciona según lo esperado.

---
