### ISSUE TITLE
Implementación del patrón Singleton en la capa de almacenamiento local del Usuario

### ISSUE THREAD

**Issue by AlejandrodePablo** [AlejandrodePablo/ed-digital-library#17]
#### 💡 Descripción
Se implementará el patrón Singleton en la clase `UserMemLocalDataSource` y en la clase `UserFileLocalDataSource` (la que será utilizada comúnmente para garantizar el almacenamiento de los datos en un archivo *.txt* tras finalizar la ejecución del programa) para garantizar que solo exista una instancia de estas clases en toda la aplicación.

---

#### 📦 UserMemLocalDataSource && UserFileLocalDataSource

1. Se implementará el patrón Singleton en las clases indicadas
2. Se realizarán los cambios pertinentes en la clase `UserPresentation` y `UserDataRepository` para llevar a cabo esta nueva funcionalidad

---

#### 🖊️ ¿Todo en orden?
- [x] Se ha implementado el patrón Singleton en la clases del apartado de almacenamiento local.
- [x] Se ha eliminado la posibilidad de instanciar la clase `UserMemLocalDataSource` y `UserFileLocalDataSource` desde cualquier otro lugar que no sea dentro de la misma clase.
- [x] Se ha verificado que la implementación del patrón Singleton funcione correctamente.

---
