### ISSUE TITLE
Consultar préstamos ya finalizados

### ISSUE THREAD

**Issue by AlejandrodePablo** [AlejandrodePablo/ed-digital-library#35]
### 🚀 *Funcionalidad de Consultar Préstamos Finalizados*

Se requiere poder consultar los préstamos que ya han sido finalizados y que el recurso digital ha sido devuelto. 

---

#### 🖥️ Consultar Préstamos Finalizados

1. Agregar método de consulta en `LoanRepository`.*(domain)*

2. Implementar método de consulta en `LoanDataRepository`.*(data)*

3. Actualizar `LoanFileLocalDataSource` con la funcionalidad de consulta.*(data)*

4. Crear caso de uso para consultar préstamos realizados.*(domain)*

5. Actualizar la capa de presentación para soportar la consulta de préstamos realizados.*(presentation)*

6. Crear test unitarios para la funcionalidad de consulta de préstamos realizados.*(test)*
---

#### 🖊️ ¿Todo en orden?

- [x] La interfaz `LoanRepository` incluye el nuevo método.
- [x] `LoanDataRepository` implementa el método delegando a `LoanFileLocalDataSource`.
- [x] `LoanFileLocalDataSource` tiene implementado el método para listar dichos préstamos.
- [x] `ListCompletedLoansUseCase` está creado y usa el método del repositorio.
- [x] `LoanPresentation` permite a los usuarios ver los préstamos devueltos.
- [x] Se han creado y pasado los test unitarios para `ListCompletedLoansUseCase`.

---
