### ISSUE TITLE
Test unitarios de funcionalidades de préstamo restantes

### ISSUE THREAD

**Issue by AlejandrodePablo** [AlejandrodePablo/ed-digital-library#36]
### 🚀 *Documentar y Realizar Test Unitarios para CreateLoanUseCase y ListUnretornedLoansUseCase*

En la realización de los casos de uso `CreateLoanUseCase` y `ListUnretornedLoansUseCase` falta por implementar los test unitarios pertinentes

---

#### 🖥️ Nombre de funcionalidad: Documentar y Realizar Test Unitarios

1. **Crear test unitarios para `CreateLoanUseCase`:**
    - Escribir test unitarios para verificar que `CreateLoanUseCase` crea un préstamo correctamente utilizando un repositorio simulado. 
    - Asegurarse de que los test cubran todos los escenarios posibles, incluyendo casos de éxito y casos de error.

2. **Crear test unitarios para `ListUnretornedLoansUseCase`:**
    - Escribir test unitarios para verificar que `ListUnretornedLoansUseCase` retorna correctamente los préstamos no devueltos utilizando un repositorio simulado. 
    - Asegurarse de que los test cubran todos los escenarios posibles.
    

---

#### 🖊️ ¿Todo en orden?

- [x] Se han creado test unitarios para `CreateLoanUseCase` que cubren todos los escenarios posibles.
- [x] Se han creado test unitarios para `ListUnretornedLoansUseCase` que cubren todos los escenarios posibles.
- [x] La cobertura de código ha sido verificada y es adecuada para los casos de uso mencionados.

---
