### ISSUE TITLE
Modificar los datos de un usuario

### ISSUE THREAD

**Issue by AlejandrodePablo** [AlejandrodePablo/ed-digital-library#9]
#### 💡 Descripción💡
La biblioteca necesita poder modificar la información perteneciente a los usuarios, ya que algunos de los campos pueden variar con el tiempo, tales como el número de teléfono o la dirección de email.

#### 🖥️ Modificación de usuarios

1. Creación del caso de uso pertinente (*UpdateUserUseCase*)
2. Actualización de las clases necesarias para implementar esta funcionalidad (*UserRepository*, *UserDataRepository*, *UserPresentation*)
3. Creación de test unitarios necesarios, (que serán actualizados en un futuro, cuando obtengamos nuevos conocimientos sobre estos).
---

#### 🖊️ ¿Todo en orden?
 - [x]  El caso de uso *UpdateUserUseCase* ha sido creado es completamente funcional.
 - [x] Las actualizaciones de las clases necesarias para implementar la nueva funcionalidad no crean conflictos con el código ya existente.
 - [x]  La opción de modificar un usuario en el menú de la interfaz de usuario está funcional y proporciona una 
 experiencia intuitiva para el usuario final.

---

#### 🗓️ 02/05/2024 ->Final
